services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vladimirtest
      - SPRING_DATASOURCE_USERNAME=helmes
      - SPRING_DATASOURCE_PASSWORD=helmes

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/main/resources/scripts/init-schema.sql:/docker-entrypoint-initdb.d/01-schemas.sql
    environment:
      - POSTGRES_DB=vladimirtest
      - POSTGRES_PASSWORD=helmes
      - POSTGRES_USER=helmes

volumes:
  db:
    external: false